project_id = "fscendubnktdtmnxiipk"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 9999
site_url = "https://mstwins.com"
additional_redirect_urls = [
  "https://mstwins.com",
  "https://mstwins.com/auth",
  "https://mstwins.com/auth?type=recovery",
  "https://7940c4cb-942f-48c4-aaf2-3eeabcbd074e.lovableproject.com",
  "https://7940c4cb-942f-48c4-aaf2-3eeabcbd074e.lovableproject.com/auth",
  "https://7940c4cb-942f-48c4-aaf2-3eeabcbd074e.lovableproject.com/auth?type=recovery",
  "http://localhost:8081/auth",
  "http://localhost:8081/auth?type=recovery",
  "http://localhost:8080/auth",
  "http://localhost:8080/auth?type=recovery"
]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true

[functions.send-welcome-email]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.health-check]
verify_jwt = false

[functions.admin-email-operations]
verify_jwt = true

[functions.secrets]
verify_jwt = true

[functions.send-migration-announcement]
verify_jwt = true

[functions.send-password-reset-email]
verify_jwt = false